slide-todo7team/slide-todo-SERVER

src/main/java/com/slide_todo/slide_todoApp/SlideTodoAppApplication.java
src/main/java/com/slide_todo/slide_todoApp/controller/MemberController.java
src/main/java/com/slide_todo/slide_todoApp/domain/member/Member.java
src/main/java/com/slide_todo/slide_todoApp/domain/member/MemberRole.java
src/main/java/com/slide_todo/slide_todoApp/dto/jwt/RefreshTokenDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/jwt/TokenPairDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/member/MemberUpdateDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/member/NicknameCheckDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/member/SigninDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/member/SignupDTO.java
src/main/java/com/slide_todo/slide_todoApp/repository/member/BaseMemberRepository.java
src/main/java/com/slide_todo/slide_todoApp/repository/member/BaseMemberRepositoryImpl.java
src/main/java/com/slide_todo/slide_todoApp/repository/member/MemberRepository.java
src/main/java/com/slide_todo/slide_todoApp/service/member/MemberService.java
src/main/java/com/slide_todo/slide_todoApp/service/member/MemberServiceImpl.java
src/main/java/com/slide_todo/slide_todoApp/util/exception/Exceptions.java
src/main/java/com/slide_todo/slide_todoApp/util/jwt/JwtProvider.java
src/main/java/com/slide_todo/slide_todoApp/util/security/SecurityConfig.java
src/test/java/com/slide_todo/slide_todoApp/TestGenerator.java
src/test/java/com/slide_todo/slide_todoApp/service/MemberTest.java

- 회원가입, 로그인, 닉네임 중복 확인, 토큰 갱신, 회원 정보 수정, 로그아웃, 회원 탈퇴 구현
- JWT 및 Redis로 블랙리스트 구현
- 기타 예외 추가
- 정규식을 통한 이메일/비밀번호 유효성 검사 추가

[FEAT] 회원 기본 기능 개발

---

src/main/java/com/slide_todo/slide_todoApp/config/SwaggerConfig.java
src/main/java/com/slide_todo/slide_todoApp/controller/MemberController.java
src/main/java/com/slide_todo/slide_todoApp/dto/jwt/RefreshTokenDTO.java
src/main/java/com/slide_todo/slide_todoApp/service/member/MemberServiceImpl.java

- 잘못 매핑된 Http Method 수정
- 이메일 유효성 검사 정규식 수정
- DTO 역직렬화 요류 수정

[FIX] PR 이슈 디버깅

---

src/main/java/com/slide_todo/slide_todoApp/domain/goal/Goal.java
src/main/java/com/slide_todo/slide_todoApp/domain/goal/GroupGoal.java
src/main/java/com/slide_todo/slide_todoApp/domain/goal/IndividualGoal.java
src/main/java/com/slide_todo/slide_todoApp/domain/group/ColorEnum.java
src/main/java/com/slide_todo/slide_todoApp/domain/group/Group.java
src/main/java/com/slide_todo/slide_todoApp/domain/group/GroupMember.java

- 그룹, 목표 domain 작업
- Group, GroupMember 와 Member 연관관계 매핑 
- Goal entity 상속관계 매핑

[CHORE] 그룹, 목표 domain 작업

---

src/main/java/com/slide_todo/slide_todoApp/domain/goal/Goal.java
src/main/java/com/slide_todo/slide_todoApp/domain/goal/GroupGoal.java
src/main/java/com/slide_todo/slide_todoApp/domain/goal/IndividualGoal.java
src/main/java/com/slide_todo/slide_todoApp/domain/group/Group.java
src/main/java/com/slide_todo/slide_todoApp/domain/note/Note.java
src/main/java/com/slide_todo/slide_todoApp/domain/todo/GroupTodo.java
src/main/java/com/slide_todo/slide_todoApp/domain/todo/IndividualTodo.java
src/main/java/com/slide_todo/slide_todoApp/domain/todo/Todo.java

- Todo 및 Note 도메인 개발
- Todo 및 Note 테스트를 위해 Group과 Goal에 생성자 추가

[FEAT] Todo 및 Note 도메인 개발

---

src/main/java/com/slide_todo/slide_todoApp/controller/GroupController.java
src/main/java/com/slide_todo/slide_todoApp/domain/group/ColorEnum.java
src/main/java/com/slide_todo/slide_todoApp/domain/group/Group.java
src/main/java/com/slide_todo/slide_todoApp/domain/group/GroupMember.java
src/main/java/com/slide_todo/slide_todoApp/dto/group/GroupCodeDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/group/GroupCreateDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/group/GroupDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/group/GroupInfoDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/group/GroupResponseDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/group/GroupTitleDTO.java
src/main/java/com/slide_todo/slide_todoApp/repository/group/GroupMemberRepository.java
src/main/java/com/slide_todo/slide_todoApp/repository/group/GroupRepository.java
src/main/java/com/slide_todo/slide_todoApp/service/group/GroupService.java
src/main/java/com/slide_todo/slide_todoApp/service/group/GroupServiceImpl.java
src/main/java/com/slide_todo/slide_todoApp/util/exception/Exceptions.java

[FEAT] 그룹 API 구현

---

src/main/java/com/slide_todo/slide_todoApp/domain/goal/Goal.java
src/main/java/com/slide_todo/slide_todoApp/domain/group/Group.java
src/main/java/com/slide_todo/slide_todoApp/domain/group/GroupMember.java
src/main/java/com/slide_todo/slide_todoApp/repository/group/GroupMemberRepository.java
src/main/java/com/slide_todo/slide_todoApp/repository/group/GroupRepository.java
src/test/java/com/slide_todo/slide_todoApp/repository/TodoRepositoryTest.java

- Group, GroupMember, Goal 리팩토링: 수정 내용은 주석으로 작성

[REFACTOR] Group, GroupMember, Goal 리팩토링

---

src/main/java/com/slide_todo/slide_todoApp/controller/GroupGoalController.java
src/main/java/com/slide_todo/slide_todoApp/controller/IndividualGoalController.java
src/main/java/com/slide_todo/slide_todoApp/dto/goal/GoalTodosResponseDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/goal/IndividualGoalTodoDTO.java
src/main/java/com/slide_todo/slide_todoApp/repository/goal/GroupGoalRepository.java
src/main/java/com/slide_todo/slide_todoApp/repository/goal/IndividualGoalRepository.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/GroupGoalService.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/GroupGoalServiceImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/IndividualGoalService.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/IndividualGoalServiceImpl.java

- 개인 목표 진행률 계산 로직 추가 
- 페이지네이션 통일

[UPDATE] 목표 API 관련 수정

---

src/main/java/com/slide_todo/slide_todoApp/controller/AdminMemberController.java
src/main/java/com/slide_todo/slide_todoApp/controller/MemberAdminController.java
src/main/java/com/slide_todo/slide_todoApp/domain/goal/Goal.java
src/main/java/com/slide_todo/slide_todoApp/domain/goal/GroupGoal.java
src/main/java/com/slide_todo/slide_todoApp/domain/goal/IndividualGoal.java
src/main/java/com/slide_todo/slide_todoApp/dto/goal/GroupGoalSearchResultDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/goal/IndividualGoalSearchResultDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/goal/admin/GroupGoalAdminDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/goal/admin/IndividualGoalAdminDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/note/NoteSearchResultDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/note/admin/GroupNoteAdminDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/note/admin/IndividualNoteAdminDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/todo/GroupTodoSearchResultDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/todo/IndividualTodoSearchResultDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/todo/admin/GroupTodoAdminDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/todo/admin/IndividualTodoListDTO.java
src/main/java/com/slide_todo/slide_todoApp/repository/goal/BaseGoalRepository.java
src/main/java/com/slide_todo/slide_todoApp/repository/goal/BaseGoalRepositoryImpl.java
src/main/java/com/slide_todo/slide_todoApp/repository/goal/GoalRepository.java
src/main/java/com/slide_todo/slide_todoApp/repository/member/BaseMemberRepositoryImpl.java
src/main/java/com/slide_todo/slide_todoApp/repository/note/BaseNoteRepository.java
src/main/java/com/slide_todo/slide_todoApp/repository/note/BaseNoteRepositoryImpl.java
src/main/java/com/slide_todo/slide_todoApp/repository/todo/BaseTodoRepository.java
src/main/java/com/slide_todo/slide_todoApp/repository/todo/BaseTodoRepositoryImpl.java
src/test/java/com/slide_todo/slide_todoApp/repository/NoteRepositoryTest.java

[FEAT] 어드민 게시글 관리 기능 개발 중

---

src/main/java/com/slide_todo/slide_todoApp/dto/goal/GroupProgressDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/group/GroupInfoDTO.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/GroupGoalServiceImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/group/GroupServiceImpl.java

- group, goal 쪽 dto 에서 name -> nickname 으로 수정

[REFACT] name -> nickname 수정

---

.github/workflows/CI-CD.yml
src/main/java/com/slide_todo/slide_todoApp/controller/MemberAdminController.java
src/main/java/com/slide_todo/slide_todoApp/domain/group/GroupMember.java
src/main/java/com/slide_todo/slide_todoApp/domain/member/Member.java
src/main/java/com/slide_todo/slide_todoApp/dto/member/MemberDetailDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/member/MemberListDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/member/MemberUpdateDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/member/SignupDTO.java
src/main/java/com/slide_todo/slide_todoApp/repository/member/BaseMemberRepository.java
src/main/java/com/slide_todo/slide_todoApp/repository/member/BaseMemberRepositoryImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/member/AdminMemberService.java
src/main/java/com/slide_todo/slide_todoApp/service/member/AdminMemberServiceImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/member/MemberServiceImpl.java
src/test/java/com/slide_todo/slide_todoApp/TestGenerator.java
src/test/java/com/slide_todo/slide_todoApp/service/MemberTest.java

- CI/CD를 위한 Github workflows 추가

[DOCS] Github workflows 추가

---

src/main/java/com/slide_todo/slide_todoApp/service/todo/TodoServiceImpl.java

[FIX] 그룹 할 일이 완료되지 않던 오류 수정

---

src/main/java/com/slide_todo/slide_todoApp/config/WebConfig.java

[CHORE] CORS 설정 추가

---

src/main/java/com/slide_todo/slide_todoApp/controller/MemberController.java
src/main/java/com/slide_todo/slide_todoApp/dto/member/DuplicationCheckDTO.java
src/main/java/com/slide_todo/slide_todoApp/service/member/MemberService.java
src/main/java/com/slide_todo/slide_todoApp/service/member/MemberServiceImpl.java
src/main/java/com/slide_todo/slide_todoApp/util/exception/Exceptions.java

- 이메일 중복 확인 API 추가
- 로그인 시 비밀번호 미일치 오류 추가

[FEAT] 이메일 중복 확인 및 비밀번호 오류 추가

---

src/main/java/com/slide_todo/slide_todoApp/controller/IndividualGoalController.java
src/main/java/com/slide_todo/slide_todoApp/dto/goal/IndividualProgressDTO.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/IndividualGoalService.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/IndividualGoalServiceImpl.java

- 개인의 모든 목표에 연결되어 있는 할 일의 진행률 조회 API 추가

[FEAT] 개인의 전체 진행률 조회 기능

---

src/main/java/com/slide_todo/slide_todoApp/controller/AdminGoalController.java
src/main/java/com/slide_todo/slide_todoApp/controller/AdminMemberController.java
src/main/java/com/slide_todo/slide_todoApp/domain/group/GroupMember.java
src/main/java/com/slide_todo/slide_todoApp/domain/member/Member.java
src/main/java/com/slide_todo/slide_todoApp/domain/todo/GroupTodo.java
src/main/java/com/slide_todo/slide_todoApp/dto/goal/GoalTitleDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/goal/admin/GoalIdsDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/goal/admin/GroupGoalDetailDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/goal/admin/IndividualGoalDetailDTO.java
src/main/java/com/slide_todo/slide_todoApp/repository/goal/BaseGoalRepository.java
src/main/java/com/slide_todo/slide_todoApp/repository/goal/BaseGoalRepositoryImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/AdminGoalService.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/AdminGoalServiceImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/member/MemberServiceImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/todo/TodoServiceImpl.java
src/main/java/com/slide_todo/slide_todoApp/util/exception/Exceptions.java

[FEAT] 어드민 목표 관리 기능 추가

---

src/main/java/com/slide_todo/slide_todoApp/domain/todo/GroupTodo.java
src/main/java/com/slide_todo/slide_todoApp/domain/todo/IndividualTodo.java
src/main/java/com/slide_todo/slide_todoApp/domain/todo/Todo.java
src/main/java/com/slide_todo/slide_todoApp/dto/goal/admin/GroupGoalDetailDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/goal/admin/IndividualGoalDetailDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/note/GroupNoteDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/note/IndividualNoteDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/todo/GroupTodoDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/todo/IndividualTodoDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/todo/TodoCreateDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/todo/TodoUpdateDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/todo/admin/GroupTodoAdminDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/todo/admin/IndividualTodoListDTO.java
src/main/java/com/slide_todo/slide_todoApp/repository/member/BaseMemberRepositoryImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/member/MemberServiceImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/todo/TodoServiceImpl.java
src/test/java/com/slide_todo/slide_todoApp/TestGenerator.java
src/test/java/com/slide_todo/slide_todoApp/repository/NoteRepositoryTest.java
src/test/java/com/slide_todo/slide_todoApp/repository/TodoRepositoryTest.java
src/test/java/com/slide_todo/slide_todoApp/service/MemberTest.java
src/test/java/com/slide_todo/slide_todoApp/service/TodoServiceTest.java

[REFACTOR] Todo 엔티티의 content 필드 삭제

---

src/main/java/com/slide_todo/slide_todoApp/controller/AdminTodoController.java

[REFACTOR] 스웨거 관련 어노테이션 수정

---

src/main/java/com/slide_todo/slide_todoApp/controller/AdminGroupController.java
src/main/java/com/slide_todo/slide_todoApp/domain/group/Group.java
src/main/java/com/slide_todo/slide_todoApp/dto/group/GroupInfoDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/group/admin/GroupFilterDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/group/admin/GroupIdDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/group/admin/GroupInfoListDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/group/admin/GroupListDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/group/admin/GroupUpdateDTO.java
src/main/java/com/slide_todo/slide_todoApp/repository/group/GroupRepository.java
src/main/java/com/slide_todo/slide_todoApp/service/group/AdminGroupService.java
src/main/java/com/slide_todo/slide_todoApp/service/group/AdminGroupServiceImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/group/GroupServiceImpl.java

[FEAT] admin-그룹관리 API 구현

---

src/main/java/com/slide_todo/slide_todoApp/domain/note/Note.java
src/main/java/com/slide_todo/slide_todoApp/repository/note/BaseNoteRepositoryImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/note/NoteServiceImpl.java

- 노트의 linkUrl 필드에 Nullable 옵션 추가

[REFACTOR] 노트의 linkUrl 필드에 Nullable 옵션 추가

---

src/main/java/com/slide_todo/slide_todoApp/domain/note/Note.java
src/main/java/com/slide_todo/slide_todoApp/service/note/NoteServiceImpl.java

- noteUpdate 메소드에 linkUrl 파라미터 추가

[FIX] noteUpdate 메소드에 linkUrl 파라미터 추가

---

src/main/java/com/slide_todo/slide_todoApp/domain/todo/Todo.java
src/main/java/com/slide_todo/slide_todoApp/dto/todo/TodoUpdateDTO.java
src/main/java/com/slide_todo/slide_todoApp/repository/goal/GroupGoalRepository.java
src/main/java/com/slide_todo/slide_todoApp/repository/group/BaseGroupRepository.java
src/main/java/com/slide_todo/slide_todoApp/repository/group/BaseGroupRepositoryImpl.java
src/main/java/com/slide_todo/slide_todoApp/repository/group/GroupRepository.java
src/main/java/com/slide_todo/slide_todoApp/service/todo/TodoServiceImpl.java
src/main/java/com/slide_todo/slide_todoApp/util/exception/Exceptions.java
src/test/java/com/slide_todo/slide_todoApp/service/TodoServiceTest.java

[FEAT] 할 일의 목표을 업데이트 할 수 있도록 수정

---

src/main/java/com/slide_todo/slide_todoApp/controller/GroupGoalController.java
src/main/java/com/slide_todo/slide_todoApp/controller/IndividualGoalController.java
src/main/java/com/slide_todo/slide_todoApp/dto/goal/SingleGoalDTO.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/GroupGoalService.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/GroupGoalServiceImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/IndividualGoalService.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/IndividualGoalServiceImpl.java

[FEAT] 단일 목표 조회 API 추가

---

src/main/java/com/slide_todo/slide_todoApp/controller/TodoController.java
src/main/java/com/slide_todo/slide_todoApp/dto/todo/GroupTodoByGoalDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/todo/IndividualTodoByGoalDTO.java
src/main/java/com/slide_todo/slide_todoApp/repository/todo/BaseTodoRepository.java
src/main/java/com/slide_todo/slide_todoApp/repository/todo/BaseTodoRepositoryImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/todo/TodoService.java
src/main/java/com/slide_todo/slide_todoApp/service/todo/TodoServiceImpl.java

[FEAT] 단일 목표에 대한 할 일 조회 API 추가

---

src/main/java/com/slide_todo/slide_todoApp/dto/goal/admin/IndividualGoalAdminDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/note/GroupNoteDTO.java

- snake case에서 camel case로 수정 과정에서 누락 된 파라미터 수정

<HOTFIX>: Refactor parameters snake case to camel case

---

src/main/java/com/slide_todo/slide_todoApp/repository/todo/TodoRepository.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/GroupGoalServiceImpl.java

- GroupTodo의 GroupMember에 대한 NPE 수정

[HOTFIX] GroupTodo의 GroupMember에 대한 NPE 수정

---

src/main/java/com/slide_todo/slide_todoApp/service/goal/GroupGoalServiceImpl.java

[HOTFIX] 그룹의 목표와 할 일이 조회되지 않던 오류 수정

---

src/main/java/com/slide_todo/slide_todoApp/controller/GroupController.java
src/main/java/com/slide_todo/slide_todoApp/controller/GroupGoalController.java
src/main/java/com/slide_todo/slide_todoApp/dto/goal/GroupGoalTodoDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/goal/IndividualGoalDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/goal/IndividualGoalTodoDTO.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/GroupGoalService.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/GroupGoalServiceImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/IndividualGoalServiceImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/group/GroupService.java
src/main/java/com/slide_todo/slide_todoApp/service/group/GroupServiceImpl.java
src/main/java/com/slide_todo/slide_todoApp/util/exception/Exceptions.java

- 그룹 방장이 탈퇴 요청 시 예외처리 
- 그룹 방장 변경 API 추가 
- 그룹 이름 / 초대코드 수정 API 추가 
- 멤버 강퇴 API 추가

[FEAT] 그룹 API 추가 요청 반영

---

src/main/java/com/slide_todo/slide_todoApp/dto/goal/GroupProgressDTO.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/GroupGoalServiceImpl.java

[REFACTOR] 오타 수정

---

src/main/java/com/slide_todo/slide_todoApp/service/goal/GroupGoalServiceImpl.java

[FIX] 그룹 목표 조회 시 Null 예외처리

---

src/main/java/com/slide_todo/slide_todoApp/service/goal/GroupGoalServiceImpl.java

[FIX] 그룹 목표 조회 Null 예외처리 수정

---

src/main/java/com/slide_todo/slide_todoApp/dto/note/GroupNoteDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/note/IndividualNoteDTO.java
src/main/java/com/slide_todo/slide_todoApp/repository/note/BaseNoteRepositoryImpl.java

- /note/get/{noteId}, /note/list/goal/{goalId}의 응답에 goal 속성 추가

[REFACTOR] 노트 관련 API 응답 본문에 목표 속성 추가

---

src/main/java/com/slide_todo/slide_todoApp/controller/NoteController.java
src/main/java/com/slide_todo/slide_todoApp/repository/note/BaseNoteRepository.java
src/main/java/com/slide_todo/slide_todoApp/repository/note/BaseNoteRepositoryImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/note/NoteService.java
src/main/java/com/slide_todo/slide_todoApp/service/note/NoteServiceImpl.java

[REFACTOR] 목표에 따른 노트 조회 응답의 페이지네이션 삭제

---

src/main/java/com/slide_todo/slide_todoApp/config/WebConfig.java

- CORS 설정 수정: https://jtodo.site에 대한 설정 추가

[CHORE] CORS 설정 수정

---

src/main/java/com/slide_todo/slide_todoApp/controller/NoteController.java
src/main/java/com/slide_todo/slide_todoApp/repository/note/BaseNoteRepository.java
src/main/java/com/slide_todo/slide_todoApp/repository/note/BaseNoteRepositoryImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/note/NoteService.java
src/main/java/com/slide_todo/slide_todoApp/service/note/NoteServiceImpl.java

[FEAT] 목표에 따른 노트 조회 시 페이지네이션 추가

---

src/main/java/com/slide_todo/slide_todoApp/service/goal/GroupGoalServiceImpl.java

[FIX] 그룹 목표 - 기여 퍼센트 오류 수정

---

src/main/java/com/slide_todo/slide_todoApp/domain/goal/Goal.java
src/main/java/com/slide_todo/slide_todoApp/domain/note/Note.java
src/main/java/com/slide_todo/slide_todoApp/service/group/GroupServiceImpl.java

- 그룹 삭제 시 외래키 관련 오류 -> domain (cascade 옵션) 수정

[FIX] 그룹 삭제 에러 수정

---

src/main/java/com/slide_todo/slide_todoApp/domain/goal/Goal.java
src/main/java/com/slide_todo/slide_todoApp/domain/group/GroupMember.java
src/main/java/com/slide_todo/slide_todoApp/domain/todo/GroupTodo.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/GroupGoalServiceImpl.java

- 그룹 탈퇴 로직 및 오류 수정 
- 탈퇴시 멤버가 생성한 목표 / 할일은 삭제하지 않음
- todo 의 memberInCharge 의 경우, 할 일이 완료된 상태면 수정 x / 완료되지 않은 상태면 null 로 비움

[FIX] 그룹탈퇴 오류 수정

---

src/main/java/com/slide_todo/slide_todoApp/config/WebConfig.java

- localhost:3001에 대한 CORS 설정 추가

[CHORE] localhost:3001에 대한 CORS 설정 추가

---

src/main/java/com/slide_todo/slide_todoApp/dto/goal/admin/GroupGoalAdminDTO.java
src/main/java/com/slide_todo/slide_todoApp/repository/goal/BaseGoalRepositoryImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/AdminGoalServiceImpl.java

[FIX] JPQL 쿼리문 오타 수정

---

src/main/java/com/slide_todo/slide_todoApp/controller/AdminMemberController.java
src/main/java/com/slide_todo/slide_todoApp/service/member/AdminMemberService.java
src/main/java/com/slide_todo/slide_todoApp/service/member/AdminMemberServiceImpl.java

[FEAT] 어드민 로그인 API 추가

---

src/main/java/com/slide_todo/slide_todoApp/service/group/AdminGroupServiceImpl.java

[FIX] 그룹 관리 오류 수정

---

src/main/java/com/slide_todo/slide_todoApp/dto/goal/GroupGoalSearchResultDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/goal/IndividualGoalSearchResultDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/goal/admin/GroupGoalAdminDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/goal/admin/IndividualGoalAdminDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/member/MemberSearchResultDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/member/admin/AdminMemberListDTO.java
src/main/java/com/slide_todo/slide_todoApp/repository/goal/BaseGoalRepository.java
src/main/java/com/slide_todo/slide_todoApp/repository/goal/BaseGoalRepositoryImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/AdminGoalServiceImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/member/AdminMemberServiceImpl.java

- 어드민 페이지에서 목록 조회 시 totalCount 필드 추가

[FEAT] 어드민 페이지에서 목록 조회 시 totalCount 필드 추가

---

src/main/java/com/slide_todo/slide_todoApp/controller/AdminGroupController.java
src/main/java/com/slide_todo/slide_todoApp/domain/group/Group.java
src/main/java/com/slide_todo/slide_todoApp/dto/group/admin/GroupListDTO.java
src/main/java/com/slide_todo/slide_todoApp/service/group/AdminGroupService.java
src/main/java/com/slide_todo/slide_todoApp/service/group/AdminGroupServiceImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/group/GroupServiceImpl.java

- 그룹장 변경 시 createdUser 도 변경되도록 수정
- totalCount, searchCount 수정

[FIX] 어드민 그룹 조회 오류 수정

---

src/main/java/com/slide_todo/slide_todoApp/domain/group/Group.java
src/main/java/com/slide_todo/slide_todoApp/domain/todo/Todo.java
src/main/java/com/slide_todo/slide_todoApp/repository/group/GroupMemberRepository.java
src/main/java/com/slide_todo/slide_todoApp/service/group/AdminGroupServiceImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/group/GroupServiceImpl.java

[FIX] 그룹 삭제방식 수정

---

src/main/java/com/slide_todo/slide_todoApp/controller/AdminGroupController.java
src/main/java/com/slide_todo/slide_todoApp/dto/group/GroupInfoDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/group/admin/GroupInfoListDTO.java
src/main/java/com/slide_todo/slide_todoApp/service/group/AdminGroupService.java
src/main/java/com/slide_todo/slide_todoApp/service/group/AdminGroupServiceImpl.java

- 검색 시 한글자만 포함되더라도 검색 가능
- 그룹 조회에 contributionRank 추가

[FIX] 어드민 그룹 - 조회 수정

---

src/main/java/com/slide_todo/slide_todoApp/service/group/AdminGroupServiceImpl.java

[FIX] 어드민 그룹 조회 - searchCount 수정

---

src/main/java/com/slide_todo/slide_todoApp/controller/AdminGoalController.java
src/main/java/com/slide_todo/slide_todoApp/controller/AdminMemberController.java
src/main/java/com/slide_todo/slide_todoApp/dto/member/admin/AdminMemberDetailDTO.java
src/main/java/com/slide_todo/slide_todoApp/dto/member/admin/AdminMemberUpdateDTO.java
src/main/java/com/slide_todo/slide_todoApp/repository/goal/BaseGoalRepository.java
src/main/java/com/slide_todo/slide_todoApp/repository/goal/BaseGoalRepositoryImpl.java
src/main/java/com/slide_todo/slide_todoApp/repository/member/BaseMemberRepositoryImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/AdminGoalService.java
src/main/java/com/slide_todo/slide_todoApp/service/goal/AdminGoalServiceImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/member/AdminMemberService.java
src/main/java/com/slide_todo/slide_todoApp/service/member/AdminMemberServiceImpl.java

- 회원 상세정보 API에서 개인 목표 속성 삭제
- 개인 목표 조회 API에서 회원 ID 쿼리 파라미터 추가

[REFACTOR] API 스펙 수정

---

src/main/java/com/slide_todo/slide_todoApp/service/group/AdminGroupServiceImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/group/GroupServiceImpl.java

- 그룹장 탈퇴 시 에러메세지 없이 그룹이 삭제되도록 변경

[REFACT] 그룹장 탈퇴 시 그룹 삭제

---

src/main/java/com/slide_todo/slide_todoApp/domain/note/Note.java
src/main/java/com/slide_todo/slide_todoApp/service/note/AdminNoteServiceImpl.java
src/main/java/com/slide_todo/slide_todoApp/service/note/NoteServiceImpl.java
src/test/java/com/slide_todo/slide_todoApp/repository/TodoRepositoryTest.java

- Note의 삭제 로직을 Hard delete로 변경

[REFACTOR] Note의 삭제 로직을 Hard delete로 변경
